/**
 * Issue #72: J1/J2リーグ全チーム シードデータ
 *
 * 2025シーズン J1: 20チーム, J2: 22チーム
 *
 * 実行: npx tsx scripts/seed-teams.ts
 */

import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

// データ定義のみ — DB投入は別途 seed-teams-run.ts で行う
export interface TeamSeed {
  name: string;
  shortName: string;
  slug: string;
  aliases: string;
  league: 'J1' | 'J2';
  emblemUrl: string;
  primaryColor: string;
  secondaryColor: string;
  stadiumName: string;
  stadiumAddress: string;
  stadiumCapacity: number;
}

/**
 * エンブレムURLは Jリーグ公式データサイト (data.j-league.or.jp) の
 * 公開画像パスを参考にしたプレースホルダーです。
 * 実運用時は公式CDNまたは自前ホスティングに差し替えてください。
 */

export const j1Teams: TeamSeed[] = [
  {
    name: '北海道コンサドーレ札幌',
    shortName: '札幌',
    slug: 'sapporo',
    aliases: 'コンサドーレ,札幌',
    league: 'J1',
    emblemUrl: '/emblems/sapporo.png',
    primaryColor: '#C8102E',
    secondaryColor: '#000000',
    stadiumName: '札幌ドーム',
    stadiumAddress: '北海道札幌市豊平区羊ケ丘1',
    stadiumCapacity: 41410,
  },
  {
    name: '鹿島アントラーズ',
    shortName: '鹿島',
    slug: 'kashima',
    aliases: 'アントラーズ,鹿島',
    league: 'J1',
    emblemUrl: '/emblems/kashima.png',
    primaryColor: '#C8102E',
    secondaryColor: '#00205B',
    stadiumName: '県立カシマサッカースタジアム',
    stadiumAddress: '茨城県鹿嶋市神向寺後山26-2',
    stadiumCapacity: 40728,
  },
  {
    name: '浦和レッドダイヤモンズ',
    shortName: '浦和',
    slug: 'urawa',
    aliases: 'レッズ,浦和',
    league: 'J1',
    emblemUrl: '/emblems/urawa.png',
    primaryColor: '#C8102E',
    secondaryColor: '#FFFFFF',
    stadiumName: '埼玉スタジアム2002',
    stadiumAddress: '埼玉県さいたま市緑区美園2-1',
    stadiumCapacity: 63700,
  },
  {
    name: '柏レイソル',
    shortName: '柏',
    slug: 'kashiwa',
    aliases: 'レイソル,柏',
    league: 'J1',
    emblemUrl: '/emblems/kashiwa.png',
    primaryColor: '#FDD000',
    secondaryColor: '#000000',
    stadiumName: '三協フロンテア柏スタジアム',
    stadiumAddress: '千葉県柏市日立台1-2-50',
    stadiumCapacity: 15349,
  },
  {
    name: 'FC東京',
    shortName: 'FC東京',
    slug: 'ftokyo',
    aliases: 'FC東京,エフシー東京',
    league: 'J1',
    emblemUrl: '/emblems/ftokyo.png',
    primaryColor: '#002FA7',
    secondaryColor: '#C8102E',
    stadiumName: '味の素スタジアム',
    stadiumAddress: '東京都調布市西町376-3',
    stadiumCapacity: 49970,
  },
  {
    name: '東京ヴェルディ',
    shortName: '東京V',
    slug: 'tokyov',
    aliases: 'ヴェルディ,東京V',
    league: 'J1',
    emblemUrl: '/emblems/tokyov.png',
    primaryColor: '#009639',
    secondaryColor: '#FFFFFF',
    stadiumName: '味の素スタジアム',
    stadiumAddress: '東京都調布市西町376-3',
    stadiumCapacity: 49970,
  },
  {
    name: 'FC町田ゼルビア',
    shortName: '町田',
    slug: 'machida',
    aliases: 'ゼルビア,町田',
    league: 'J1',
    emblemUrl: '/emblems/machida.png',
    primaryColor: '#003DA5',
    secondaryColor: '#FFFFFF',
    stadiumName: '町田GIONスタジアム',
    stadiumAddress: '東京都町田市野津田町2035',
    stadiumCapacity: 15320,
  },
  {
    name: '川崎フロンターレ',
    shortName: '川崎F',
    slug: 'kawasakif',
    aliases: 'フロンターレ,川崎',
    league: 'J1',
    emblemUrl: '/emblems/kawasakif.png',
    primaryColor: '#009FE3',
    secondaryColor: '#000000',
    stadiumName: 'Uvanceとどろきスタジアム by Fujitsu',
    stadiumAddress: '神奈川県川崎市中原区等々力1-1',
    stadiumCapacity: 26232,
  },
  {
    name: '横浜Ｆ・マリノス',
    shortName: '横浜FM',
    slug: 'yokohamafm',
    aliases: 'マリノス,横浜FM',
    league: 'J1',
    emblemUrl: '/emblems/yokohamafm.png',
    primaryColor: '#003399',
    secondaryColor: '#C8102E',
    stadiumName: '日産スタジアム',
    stadiumAddress: '神奈川県横浜市港北区小机町3300',
    stadiumCapacity: 72327,
  },
  {
    name: '湘南ベルマーレ',
    shortName: '湘南',
    slug: 'shonan',
    aliases: 'ベルマーレ,湘南',
    league: 'J1',
    emblemUrl: '/emblems/shonan.png',
    primaryColor: '#009639',
    secondaryColor: '#009FE3',
    stadiumName: 'レモンガススタジアム平塚',
    stadiumAddress: '神奈川県平塚市大原1-1',
    stadiumCapacity: 15380,
  },
  {
    name: 'アルビレックス新潟',
    shortName: '新潟',
    slug: 'niigata',
    aliases: 'アルビレックス,新潟',
    league: 'J1',
    emblemUrl: '/emblems/niigata.png',
    primaryColor: '#FF6600',
    secondaryColor: '#002FA7',
    stadiumName: 'デンカビッグスワンスタジアム',
    stadiumAddress: '新潟県新潟市中央区清五郎67-12',
    stadiumCapacity: 42300,
  },
  {
    name: '名古屋グランパス',
    shortName: '名古屋',
    slug: 'nagoya',
    aliases: 'グランパス,名古屋',
    league: 'J1',
    emblemUrl: '/emblems/nagoya.png',
    primaryColor: '#C8102E',
    secondaryColor: '#FF8200',
    stadiumName: '豊田スタジアム',
    stadiumAddress: '愛知県豊田市千石町7-2',
    stadiumCapacity: 45000,
  },
  {
    name: '京都サンガF.C.',
    shortName: '京都',
    slug: 'kyoto',
    aliases: 'サンガ,京都',
    league: 'J1',
    emblemUrl: '/emblems/kyoto.png',
    primaryColor: '#4B0082',
    secondaryColor: '#FFFFFF',
    stadiumName: 'サンガスタジアム by KYOCERA',
    stadiumAddress: '京都府亀岡市吉川町吉田藪ノ下',
    stadiumCapacity: 21600,
  },
  {
    name: 'ガンバ大阪',
    shortName: 'G大阪',
    slug: 'gosaka',
    aliases: 'ガンバ,G大阪',
    league: 'J1',
    emblemUrl: '/emblems/gosaka.png',
    primaryColor: '#002FA7',
    secondaryColor: '#000000',
    stadiumName: 'パナソニックスタジアム吹田',
    stadiumAddress: '大阪府吹田市千里万博公園3-3',
    stadiumCapacity: 39694,
  },
  {
    name: 'セレッソ大阪',
    shortName: 'C大阪',
    slug: 'cosaka',
    aliases: 'セレッソ,C大阪',
    league: 'J1',
    emblemUrl: '/emblems/cosaka.png',
    primaryColor: '#E84B8A',
    secondaryColor: '#002FA7',
    stadiumName: 'ヨドコウ桜スタジアム',
    stadiumAddress: '大阪府大阪市東住吉区長居公園1-1',
    stadiumCapacity: 24500,
  },
  {
    name: 'ヴィッセル神戸',
    shortName: '神戸',
    slug: 'kobe',
    aliases: 'ヴィッセル,神戸',
    league: 'J1',
    emblemUrl: '/emblems/kobe.png',
    primaryColor: '#8B0000',
    secondaryColor: '#FFFFFF',
    stadiumName: 'ノエビアスタジアム神戸',
    stadiumAddress: '兵庫県神戸市兵庫区御崎町1-2-2',
    stadiumCapacity: 30132,
  },
  {
    name: 'サンフレッチェ広島',
    shortName: '広島',
    slug: 'hiroshima',
    aliases: 'サンフレッチェ,広島',
    league: 'J1',
    emblemUrl: '/emblems/hiroshima.png',
    primaryColor: '#4B0082',
    secondaryColor: '#FFFFFF',
    stadiumName: 'エディオンピースウイング広島',
    stadiumAddress: '広島県広島市中区基町15',
    stadiumCapacity: 28500,
  },
  {
    name: 'アビスパ福岡',
    shortName: '福岡',
    slug: 'fukuoka',
    aliases: 'アビスパ,福岡',
    league: 'J1',
    emblemUrl: '/emblems/fukuoka.png',
    primaryColor: '#002FA7',
    secondaryColor: '#FFFFFF',
    stadiumName: 'ベスト電器スタジアム',
    stadiumAddress: '福岡県福岡市博多区東平尾公園2-1-1',
    stadiumCapacity: 22563,
  },
  {
    name: 'サガン鳥栖',
    shortName: '鳥栖',
    slug: 'tosu',
    aliases: 'サガン,鳥栖',
    league: 'J1',
    emblemUrl: '/emblems/tosu.png',
    primaryColor: '#009FE3',
    secondaryColor: '#E84B8A',
    stadiumName: '駅前不動産スタジアム',
    stadiumAddress: '佐賀県鳥栖市京町812',
    stadiumCapacity: 24490,
  },
  {
    name: 'ジュビロ磐田',
    shortName: '磐田',
    slug: 'iwata',
    aliases: 'ジュビロ,磐田',
    league: 'J1',
    emblemUrl: '/emblems/iwata.png',
    primaryColor: '#009FE3',
    secondaryColor: '#FFFFFF',
    stadiumName: 'ヤマハスタジアム（磐田）',
    stadiumAddress: '静岡県磐田市新貝2500',
    stadiumCapacity: 15165,
  },
];

export const j2Teams: TeamSeed[] = [
  {
    name: 'ベガルタ仙台',
    shortName: '仙台',
    slug: 'sendai',
    aliases: 'ベガルタ,仙台',
    league: 'J2',
    emblemUrl: '/emblems/sendai.png',
    primaryColor: '#FFD700',
    secondaryColor: '#000000',
    stadiumName: 'ユアテックスタジアム仙台',
    stadiumAddress: '宮城県仙台市泉区七北田字柳78',
    stadiumCapacity: 19694,
  },
  {
    name: 'モンテディオ山形',
    shortName: '山形',
    slug: 'yamagata',
    aliases: 'モンテディオ,山形',
    league: 'J2',
    emblemUrl: '/emblems/yamagata.png',
    primaryColor: '#002FA7',
    secondaryColor: '#FFFFFF',
    stadiumName: 'NDソフトスタジアム山形',
    stadiumAddress: '山形県天童市山王1-1',
    stadiumCapacity: 20515,
  },
  {
    name: 'いわきFC',
    shortName: 'いわき',
    slug: 'iwaki',
    aliases: 'いわきFC,いわき',
    league: 'J2',
    emblemUrl: '/emblems/iwaki.png',
    primaryColor: '#C8102E',
    secondaryColor: '#FFFFFF',
    stadiumName: 'いわきグリーンフィールド',
    stadiumAddress: '福島県いわき市常磐上湯長谷町釜之前50-1',
    stadiumCapacity: 5000,
  },
  {
    name: '水戸ホーリーホック',
    shortName: '水戸',
    slug: 'mito',
    aliases: 'ホーリーホック,水戸',
    league: 'J2',
    emblemUrl: '/emblems/mito.png',
    primaryColor: '#002FA7',
    secondaryColor: '#FFFFFF',
    stadiumName: 'ケーズデンキスタジアム水戸',
    stadiumAddress: '茨城県水戸市小吹町2058-1',
    stadiumCapacity: 12000,
  },
  {
    name: '栃木SC',
    shortName: '栃木',
    slug: 'tochigi',
    aliases: '栃木SC,栃木',
    league: 'J2',
    emblemUrl: '/emblems/tochigi.png',
    primaryColor: '#FFD700',
    secondaryColor: '#000000',
    stadiumName: 'カンセキスタジアムとちぎ',
    stadiumAddress: '栃木県宇都宮市西川田4-1-1',
    stadiumCapacity: 25244,
  },
  {
    name: 'ザスパ群馬',
    shortName: '群馬',
    slug: 'gunma',
    aliases: 'ザスパ,群馬',
    league: 'J2',
    emblemUrl: '/emblems/gunma.png',
    primaryColor: '#009639',
    secondaryColor: '#FFFFFF',
    stadiumName: '正田醤油スタジアム群馬',
    stadiumAddress: '群馬県前橋市敷島町66',
    stadiumCapacity: 15253,
  },
  {
    name: '大宮アルディージャ',
    shortName: '大宮',
    slug: 'omiya',
    aliases: 'アルディージャ,大宮',
    league: 'J2',
    emblemUrl: '/emblems/omiya.png',
    primaryColor: '#FF6600',
    secondaryColor: '#FFFFFF',
    stadiumName: 'NACK5スタジアム大宮',
    stadiumAddress: '埼玉県さいたま市大宮区高鼻町4',
    stadiumCapacity: 15500,
  },
  {
    name: 'ジェフユナイテッド千葉',
    shortName: '千葉',
    slug: 'chiba',
    aliases: 'ジェフ,千葉',
    league: 'J2',
    emblemUrl: '/emblems/chiba.png',
    primaryColor: '#009639',
    secondaryColor: '#C8102E',
    stadiumName: 'フクダ電子アリーナ',
    stadiumAddress: '千葉県千葉市中央区川崎町1-20',
    stadiumCapacity: 19781,
  },
  {
    name: '横浜FC',
    shortName: '横浜FC',
    slug: 'yokohamafc',
    aliases: '横浜FC',
    league: 'J2',
    emblemUrl: '/emblems/yokohamafc.png',
    primaryColor: '#009FE3',
    secondaryColor: '#FFFFFF',
    stadiumName: 'ニッパツ三ツ沢球技場',
    stadiumAddress: '神奈川県横浜市神奈川区三ツ沢西町3-1',
    stadiumCapacity: 15454,
  },
  {
    name: 'ヴァンフォーレ甲府',
    shortName: '甲府',
    slug: 'kofu',
    aliases: 'ヴァンフォーレ,甲府',
    league: 'J2',
    emblemUrl: '/emblems/kofu.png',
    primaryColor: '#002FA7',
    secondaryColor: '#C8102E',
    stadiumName: 'JITリサイクルインクスタジアム',
    stadiumAddress: '山梨県甲府市小瀬町840',
    stadiumCapacity: 17000,
  },
  {
    name: '清水エスパルス',
    shortName: '清水',
    slug: 'shimizu',
    aliases: 'エスパルス,清水',
    league: 'J2',
    emblemUrl: '/emblems/shimizu.png',
    primaryColor: '#FF6600',
    secondaryColor: '#FFFFFF',
    stadiumName: 'IAIスタジアム日本平',
    stadiumAddress: '静岡県静岡市清水区村松3880-1',
    stadiumCapacity: 20248,
  },
  {
    name: '藤枝MYFC',
    shortName: '藤枝',
    slug: 'fujieda',
    aliases: '藤枝MYFC,藤枝',
    league: 'J2',
    emblemUrl: '/emblems/fujieda.png',
    primaryColor: '#009639',
    secondaryColor: '#FFD700',
    stadiumName: '藤枝総合運動公園サッカー場',
    stadiumAddress: '静岡県藤枝市善左衛門1-11-1',
    stadiumCapacity: 5880,
  },
  {
    name: 'V・ファーレン長崎',
    shortName: '長崎',
    slug: 'nagasaki',
    aliases: 'Vファーレン,長崎',
    league: 'J2',
    emblemUrl: '/emblems/nagasaki.png',
    primaryColor: '#002FA7',
    secondaryColor: '#FF6600',
    stadiumName: 'ピーススタジアム',
    stadiumAddress: '長崎県長崎市幸町7-1',
    stadiumCapacity: 20000,
  },
  {
    name: 'ファジアーノ岡山',
    shortName: '岡山',
    slug: 'okayama',
    aliases: 'ファジアーノ,岡山',
    league: 'J2',
    emblemUrl: '/emblems/okayama.png',
    primaryColor: '#C8102E',
    secondaryColor: '#FFFFFF',
    stadiumName: 'シティライトスタジアム',
    stadiumAddress: '岡山県岡山市北区いずみ町2-1-3',
    stadiumCapacity: 20000,
  },
  {
    name: 'レノファ山口FC',
    shortName: '山口',
    slug: 'yamaguchi',
    aliases: 'レノファ,山口',
    league: 'J2',
    emblemUrl: '/emblems/yamaguchi.png',
    primaryColor: '#FF6600',
    secondaryColor: '#002FA7',
    stadiumName: '維新みらいふスタジアム',
    stadiumAddress: '山口県山口市維新公園4-1-1',
    stadiumCapacity: 15400,
  },
  {
    name: '徳島ヴォルティス',
    shortName: '徳島',
    slug: 'tokushima',
    aliases: 'ヴォルティス,徳島',
    league: 'J2',
    emblemUrl: '/emblems/tokushima.png',
    primaryColor: '#4B0082',
    secondaryColor: '#009639',
    stadiumName: '鳴門・大塚スポーツパーク ポカリスエットスタジアム',
    stadiumAddress: '徳島県鳴門市撫養町立岩字四枚61',
    stadiumCapacity: 11000,
  },
  {
    name: '愛媛FC',
    shortName: '愛媛',
    slug: 'ehime',
    aliases: '愛媛FC,愛媛',
    league: 'J2',
    emblemUrl: '/emblems/ehime.png',
    primaryColor: '#FF6600',
    secondaryColor: '#002FA7',
    stadiumName: 'ニンジニアスタジアム',
    stadiumAddress: '愛媛県松山市上野町乙46',
    stadiumCapacity: 15692,
  },
  {
    name: 'FC今治',
    shortName: '今治',
    slug: 'imabari',
    aliases: 'FC今治,今治',
    league: 'J2',
    emblemUrl: '/emblems/imabari.png',
    primaryColor: '#002FA7',
    secondaryColor: '#FFD700',
    stadiumName: '今治里山スタジアム',
    stadiumAddress: '愛媛県今治市高橋ふれあいの丘1-3',
    stadiumCapacity: 5500,
  },
  {
    name: 'ロアッソ熊本',
    shortName: '熊本',
    slug: 'kumamoto',
    aliases: 'ロアッソ,熊本',
    league: 'J2',
    emblemUrl: '/emblems/kumamoto.png',
    primaryColor: '#C8102E',
    secondaryColor: '#000000',
    stadiumName: 'えがお健康スタジアム',
    stadiumAddress: '熊本県熊本市東区平山町2776',
    stadiumCapacity: 32000,
  },
  {
    name: '大分トリニータ',
    shortName: '大分',
    slug: 'oita',
    aliases: 'トリニータ,大分',
    league: 'J2',
    emblemUrl: '/emblems/oita.png',
    primaryColor: '#002FA7',
    secondaryColor: '#FFFFFF',
    stadiumName: 'レゾナックドーム大分',
    stadiumAddress: '大分県大分市横尾1351',
    stadiumCapacity: 40000,
  },
  {
    name: '鹿児島ユナイテッドFC',
    shortName: '鹿児島',
    slug: 'kagoshima',
    aliases: '鹿児島ユナイテッド,鹿児島',
    league: 'J2',
    emblemUrl: '/emblems/kagoshima.png',
    primaryColor: '#002FA7',
    secondaryColor: '#FFFFFF',
    stadiumName: '白波スタジアム',
    stadiumAddress: '鹿児島県鹿児島市与次郎2-2-2',
    stadiumCapacity: 19934,
  },
  {
    name: 'カターレ富山',
    shortName: '富山',
    slug: 'toyama',
    aliases: 'カターレ,富山',
    league: 'J2',
    emblemUrl: '/emblems/toyama.png',
    primaryColor: '#002FA7',
    secondaryColor: '#FFFFFF',
    stadiumName: '富山県総合運動公園陸上競技場',
    stadiumAddress: '富山県富山市南中田368-1',
    stadiumCapacity: 25258,
  },
];

export const allTeams = [...j1Teams, ...j2Teams];
